authorizedips:
  - "127.0.0.1"
  - "10.0.2.2"
  - "10.172.2.215"
  - "10.172.2.4"
# fields from the borrowers table to be sent by the today and all services
#borrowerfields:
# - "surname"
# - "firstname"
# - "zipcode"
